# Generated by Django 3.2.13 on 2022-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_products',
            field=models.ManyToManyField(related_name='like_users', to='products.Product'),
        ),
    ]
