# Generated by Django 3.2.13 on 2022-11-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0005_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
