# Generated by Django 3.2.13 on 2022-11-10 01:11


from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('pay', models.CharField(max_length=80)),
                ('Description', models.TextField()),
                ('delivery', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.TextField()),

                ('product_image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='imgaes/')),


            ],
        ),
    ]
