# Generated by Django 3.2.13 on 2022-11-10 05:23

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='imgaes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
