# Generated by Django 3.2.13 on 2022-11-10 06:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221110_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='imgaes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='imgaes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='imgaes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='description_images/'),
        ),
    ]
