# Generated by Django 3.2.13 on 2022-11-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221110_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
