# Generated by Django 3.2.13 on 2022-11-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221111_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Description',
        ),
        migrations.AddField(
            model_name='product',
            name='Description1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
