# Generated by Django 3.2.13 on 2022-11-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sale'),
        ('products', '0004_alter_product_sale'),
    ]

    operations = [
    ]
